(define (problem bw-12step)
    (:domain blocks_world)
    (:objects A B C D E F G)
    (:init (on-table A) (clear A)
    	 (on-table B) (clear B)
    	 (on-table G)
    	 (on F G)
    	 (on E F)
    	 (on D E)
    	 (on C D) (clear C))
    (:goal (and (on B C) (on-table A) (on F A) (on C D)))
)